#!/usr/bin/python
import numpy as np
import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BOARD)
GPIO.setup(11,GPIO.OUT) #pin11=output
p = GPIO.PWM(11, 50)    #sets as a a PWM pin
p.start(0)              #starts running PWM (sets to 0)
p.ChangeDutyCycle(3)
sleep(2)
p.ChangeDutyCycle(12)
sleep(1)
p.stop()
GPIO.cleanup()
